site_name: Alex's Personal Wiki 
theme: readthedocs
markdown_extensions:
        - mdx_math
extra_javascript: 
        - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
        - assets/mathjaxhelper.js
